Fix missing id on background in activities causing FATAL EXCEPTION :
java.lang.RuntimeException: All children of ConstraintLayout must have ids to use ConstraintSet
        at androidx.constraintlayout.widget.ConstraintSet.readFallback(ConstraintSet.java:459)